apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: httpbin-dev
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;

        location = /status/200 {
          limit_except GET {
            deny all;
          }
          proxy_pass http://httpbin-service:80;
        }

        location / {
          return 404;
        }
      }
    }
